[package]
name = "corelib"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Whittle <jonathan.m.whittle>"]

[dependencies]
bincode = "1.3.3"
sled = "0.34.7"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tracing = { version = "0.1.37" }